pipeline {
    agent any

    parameters {
        string(name: 'PERSON', defaultValue: 'Mr Jenkins', description: 'Who should I say hello to?')
   }

    
    stages {
        stage('Hello') {
            steps {
                echo 'Hello I am talking from github'

                echo "Hello ${params.PERSON}"
            }
        }

            stage('Checkout') {
        steps {
            git branch: 'main',
                url: 'https://github.com/iamakashk/devops-full-stack-project-example.git'
        }
    }
    }
}
