pipeline {
    agent any

    parameters {
        string(name: 'github_url', defaultValue: 'Mr Jenkins', description: 'Who should I say hello to?')
   }

    
    stages {
        stage('Hello') {
            steps {
                echo 'Hello I am talking from github'

                echo "Hello ${params.github_url}"
            }
        }

            stage('Checkout') {
        steps {
            git branch: 'main',
                url: "${params.github_url}"
        }
    }
    }
}
